# To make sure we have the node, npm, and golang binaries
FROM node:21.5.0-slim AS node
FROM golang:1.22.5 AS golang

# This is the actual image we will use
FROM ubuntu:24.04

# Go to a temporary directory until we install all the dependencies
RUN mkdir -p /app/temp
WORKDIR /app/temp

# Install system dependencies
RUN apt-get update && \
    apt-get install -y wget git && \
    rm -rf /var/lib/apt/lists/*

# Copy node and npm binaries from the node image
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=node /usr/local/bin/node /usr/local/bin/node
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm

# Copy the golang binaries from the golang image
COPY --from=golang /usr/local/go /usr/local/go
ENV PATH "$PATH:/usr/local/go/bin"

# Install task
RUN wget https://github.com/go-task/task/releases/download/v3.37.2/task_linux_amd64.tar.gz && \
    tar -xzf task_linux_amd64.tar.gz && \
    mv ./task /usr/local/bin/task && \
    chmod 777 /usr/local/bin/task

# Install GitHub CLI
RUN wget https://github.com/cli/cli/releases/download/v2.52.0/gh_2.52.0_linux_amd64.tar.gz && \
    tar -xzf gh_2.52.0_linux_amd64.tar.gz && \
    mv gh_2.52.0_linux_amd64/bin/gh /usr/local/bin/gh && \
    chmod 777 /usr/local/bin/gh

# Install air
RUN wget https://github.com/cosmtrek/air/releases/download/v1.52.3/air_1.52.3_linux_amd64.tar.gz && \
    tar -xzf air_1.52.3_linux_amd64.tar.gz && \
    mv ./air /usr/local/bin/air && \
    chmod 777 /usr/local/bin/air

# Install node packages
RUN npm install --global cloc@2.0.0-cloc && \
    npm install --global tailwindcss@3.4.4 && \
    npm install --global daisyui@4.12.10

# Delete the temporary directory and go to the app directory
RUN rm -rf /app/temp
WORKDIR /app

# Add the startup script on every bash session
COPY scripts/startup.sh /usr/local/bin/startup.sh
RUN echo "\n\n" >> /root/.bashrc && \
    cat /usr/local/bin/startup.sh >> /root/.bashrc

# Command just to keep the container running
CMD ["tail", "-f", "/dev/null"]
